### PR TITLE
Create issue templates

### PR DESCRIPTION
**Pull request by Hoverbear**
Same as https://github.com/pingcap/grpc-rs/pull/221.

### CODE REVIEW

**Comment by overvenus** [comment]
PTAL @BusyJay @siddontang

**Comment by BusyJay** [comment]
Is it too heavy for such a simple project?

**Comment by Hoverbear** [comment]
@BusyJay I tried to keep it quite simple to reflect the project's simplicity. If we were not also maintaining several other repositories I think it would be not so useful. But in this situation perhaps it can help create more consistent bug reporting.

At worst, it's 1 more click creating an issue. The PR templates are only currently used for automation, so most users won't see them.

**Comment by Hoverbear** [comment]
@siddontang / @overvenus I cannot merge with fail-rs, can you please merge it?

**Pull request merged**
